### ISSUE TITLE
[FaloopIntegration]EAが有効になっている報告が正しく表示されない

### ISSUE THREAD

**Issue by ssss142** [SlashNephy/Divination#641]
アーリーアクセス報告（以下EA）が有効になっている報告が正常に表示されない。
※EAは報告者（EA）権限持ちが先行的に湧いたことを知ることができる機能。（国内外DCによって違いあり）

1. 現在のモブに表示されるがチャットの湧いた表示がされたりされなかったりする。
2. 現在のモブの時間表記が継続計算される。（WEB上では通常報告移行時に時間がリセットされる）

xllog上の表示されなかったモブのログ
```
06:41:50.883 | DBG | [FaloopIntegration] Event "message" = "[{\"type\":\"mob\",\"subType\":\"report\",\"data\":{\"action\":\"spawn\",\"id\":{\"mobId\":\"tarchia\",\"worldId\":\"ifrit\"},\"mobId\":8900,\"worldId\":59,\"zoneInstance\":0,\"data\":{\"zoneId\":815,\"zonePoiIds\":[963],\"timestamp\":\"2024-04-04T21:41:50.760Z\",\"reporters\":[],\"isScheduled\":true,\"window\":1,\"stage\":null}}}]"
```
表示されたもの
```
06:53:53.854 | DBG | [FaloopIntegration] Event "message" = "[{\"type\":\"mob\",\"subType\":\"report\",\"data\":{\"action\":\"spawn\",\"id\":{\"mobId\":\"orghana\",\"worldId\":\"fenrir\"},\"mobId\":5986,\"worldId\":46,\"zoneInstance\":0,\"data\":{\"zoneId\":622,\"zonePoiIds\":[882],\"timestamp\":\"2024-04-04T21:53:53.746Z\",\"reporters\":[{\"id\":****,\"name\":\"****\"}],\"isScheduled\":true,\"window\":1,\"stage\":null}}}]"
```
一部マスクあり
あとはたまにERRも発生。
```
06:59:05.798 | ERR | [FaloopIntegration] HandleOnMessage
	System.ArgumentNullException: Value cannot be null. (Parameter 'source')
	   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
	   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
	   at Divination.FaloopIntegration.FaloopIntegration.OnMobSpawn(MobSpawnEvent ev, Int32 channel) in D:\a\Divination\Divination\FaloopIntegration\FaloopIntegration.cs:line 164
	   at Divination.FaloopIntegration.FaloopIntegration.OnMobReport(MobReportData data) in D:\a\Divination\Divination\FaloopIntegration\FaloopIntegration.cs:line 143
	   at Divination.FaloopIntegration.Faloop.FaloopSocketIOClient.HandleOnMessage(SocketIOResponse response) in D:\a\Divination\Divination\FaloopIntegration\Faloop\FaloopSocketIOClient.cs:line 171
```

**Comment by SlashNephy** [comment]
こんにちは、報告ありがとうございます！
私はアーリーアクセス権限を持っていませんが、提供いただいたログを元に修正してみます

**Comment by ssss142** [comment]
報告オプションが多数あるのでこれ以外にも想定外なものがあるかもしれません。
開発者結構フランクなので聞いたら教えてくれるかもしれませんが.....

**Comment by SlashNephy** [comment]
報告者はスポーン地点を選ばずに湧き報告できると思うのですが、その場合に通知できなかったようです
https://github.com/SlashNephy/Divination/releases/tag/6.58.3 で修正したので、数分でアップデートが配信されると思います

**Comment by ssss142** [comment]
なるほど先に湧いた報告だけEAして後ほど座標設定する方もいますので勘違いした感じでしたね。
対応ありがとうございます。

**Comment by ssss142** [comment]
EA座標なしで表示されずERRでした。
```
07:32:11.661 | DBG | [FaloopIntegration] Event "message" = "[{\"type\":\"mob\",\"subType\":\"report\",\"data\":{\"action\":\"spawn\",\"id\":{\"mobId\":\"lampalagua\",\"worldId\":\"durandal\"},\"mobId\":2959,\"worldId\":92,\"zoneInstance\":0,\"data\":{\"zoneId2\":\"eastern_thanalan\",\"zoneId\":145,\"location\":null,\"timestamp\":\"2024-04-06T22:32:11.535Z\",\"reporters\":[{\"id\":***,\"name\":\"***\"}],\"isScheduled\":true,\"window\":1,\"stage\":null}}}]"
07:32:11.675 | ERR | [FaloopIntegration] HandleOnMessage
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at Divination.FaloopIntegration.FaloopIntegration.OnMobSpawn(MobSpawnEvent ev, Int32 channel) in D:\a\Divination\Divination\FaloopIntegration\FaloopIntegration.cs:line 173
	   at Divination.FaloopIntegration.FaloopIntegration.OnMobReport(MobReportData data) in D:\a\Divination\Divination\FaloopIntegration\FaloopIntegration.cs:line 141
	   at Divination.FaloopIntegration.Faloop.FaloopSocketIOClient.HandleOnMessage(SocketIOResponse response) in D:\a\Divination\Divination\FaloopIntegration\Faloop\FaloopSocketIOClient.cs:line 171
07:33:03.031 | DBG | [FaloopIntegration] Event "message" = "[{\"type\":\"mob\",\"subType\":\"report\",\"data\":{\"action\":\"spawn_location\",\"id\":{\"mobId\":\"lampalagua\",\"worldId\":\"durandal\"},\"mobId\":2959,\"worldId\":92,\"zoneInstance\":0,\"data\":{\"zoneId\":145,\"zonePoiId\":230}}}]"
07:33:07.974 | DBG | [FaloopIntegration] Event "message" = "[{\"type\":\"mob\",\"subType\":\"report\",\"data\":{\"action\":\"spawn_release\",\"id\":{\"mobId\":\"lampalagua\",\"worldId\":\"durandal\"},\"mobId\":2959,\"worldId\":92,\"zoneInstance\":0,\"data\":{\"timestamp\":1712442787849}}}]"

```
ユーザーIDとキャラ名はマスクしています。

**Comment by SlashNephy** [comment]
こちらで対応してみました
https://github.com/SlashNephy/Divination/releases/tag/6.58.4

**Comment by ssss142** [comment]
最長ポップタイム超えてもポップしなかったSモブに対して行うことができる機能「倒された報告」をされたとき異常の日付になる。

`16:19:29.616 | DBG | [FaloopIntegration] Event "message" = "[{\"type\":\"mob\",\"subType\":\"report\",\"data\":{\"action\":\"death\",\"id\":{\"mobId\":\"minhocao\",\"worldId\":\"ultima\"},\"data\":{\"num\":1,\"snipedNum\":1}}}]"`

>  ミニョーカオンUltima が討伐されました。 (738996日前)

**Comment by SlashNephy** [comment]
いま v6.58.10 をリリースしたところです。
[Release 6.58.10 · SlashNephy/Divination](https://github.com/SlashNephy/Divination/releases/tag/6.58.10)
問題が解決していることを確認したら、Issue をクローズしていただけますか？

**Comment by ssss142** [comment]
遅れましたが動作改善確認しました。
