### ISSUE TITLE
AetheryteLinkInChat

### ISSUE THREAD

**Issue by zxwqwq** [SlashNephy/Divination#682]
**Which plugin are you referring to?**
AetheryteLinkInChat

**Describe the bug**
fail to load the plugin

**Additional context**
12:46:18.610 | ERR | [LOCALPLUGIN] Error while loading "AetheryteLinkInChat", failed to bind and call the plugin constructor
	System.AggregateException: Failed to create Divination.AetheryteLinkInChat.AetheryteLinkInChat (ctor invocation) (Exception has been thrown by the target of an invocation.)
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.NullReferenceException: Object reference not set to an instance of an object.
	   at Dalamud.Divination.Common.Api.Command.CommandProcessor..ctor(String pluginName, String prefix, IChatGui chatGui, IChatClient chatClient, ICommandManager commandManager) in D:\a\Divination\Divination\Common\Api\Command\CommandProcessor.cs:line 42
	   at Dalamud.Divination.Common.Api.DivinationApi`2.<get_Command>b__13_0() in D:\a\Divination\Divination\Common\Api\DivinationApi.cs:line 51
	   at Dalamud.Divination.Common.Api.ServiceContainer.GetOrPutOptional[T](Func`1 initializer) in D:\a\Divination\Divination\Common\Api\ServiceContainer.cs:line 48
	   at Dalamud.Divination.Common.Api.DivinationApi`2..ctor(IDalamudApi api, Assembly assembly, IDivinationPluginApi`2 plugin) in D:\a\Divination\Divination\Common\Api\DivinationApi.cs:line 32
	   at Dalamud.Divination.Common.Boilerplate.DivinationPlugin`3..ctor(IDalamudPluginInterface pluginInterface) in D:\a\Divination\Divination\Common\Boilerplate\DivinationPlugin{TPlugin,TConfiguration,TDefinition}.cs:line 26
	   at Divination.AetheryteLinkInChat.AetheryteLinkInChat..ctor(IDalamudPluginInterface pluginInterface) in D:\a\Divination\Divination\AetheryteLinkInChat\AetheryteLinkInChat.cs:line 38
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
	   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0()
	--- End of stack trace from previous location ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope)
	   --- End of inner exception stack trace ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope)
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass75_0.<<CreatePluginInstance>g__Create|0>d.MoveNext()
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.CreatePluginInstance(LocalPluginManifest manifest, IServiceScope scope, Type type, DalamudPluginInterface dalamudInterface)
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading)

**Comment by SlashNephy** [comment]
A new plugin version v7.0.2.0 is now available.
